### PR TITLE
fix release process for fusionauth helm chart

### PR DESCRIPTION
**Pull request by lanceatdr**
**What this PR does / why we need it**:
* This PR fixes the release process to work with creating a github release that is served via an index file in github pages
* Adds a post release step to install the release to a kind cluster and ensure the proper version gets installed

**Special notes for your reviewer**:
* If pages is served by a branch other than `gh-pages` this will require modifications.  @robotdan @mooreds please confirm which branch is configured for github pages prior to merge.

** A working example of the release process can be found [here](https://github.com/drivenrole/charts/actions/runs/1121129787)

### CODE REVIEW

**Comment by drpebcak** [comment]
Pages is configured to use `master` in this repo right now.

**Comment by lanceatdr** [comment]
Thx @drpebcak. I updated the action to push the updated `index.yaml` back to `master`.  This PR is good to merge after review.

**Review by drpebcak — APPROVED** [review]
lgtm

**Comment by drpebcak** [comment]
@lanceatdr this didn't do quite what I expected.. I'm not super familiar with chart-releaser, but in this case I merged the MR and then created a tag (0.10.0).. github actions starting running, and then an additional tag was created (fusionauth-0.10.0). The duplicate tag is probably not desirable. Is there something we can do to prevent this?

**Comment by lanceatdr** [comment]
@drpebcak good catch.  I did not notice it was naming releases different than the tag pushed.  I figured out a way to get `chart-releaser` to name releases the same as the version tag being pushed.  Will submit that change in another PR.

**Comment by drpebcak** [comment]
@lanceatdr might as well keep the conversation going here - Looks like it doesn't want to add to the tag I made, so it errored out: https://github.com/FusionAuth/charts/runs/3355226505?check_suite_focus=true#step:6:19

**Comment by lanceatdr** [comment]
@drpebcak I tested again in my fork [here](https://github.com/drivenrole/charts/actions/runs/1143992223) and it worked as expected.  In testing I'm running the following to trigger a build:

```
git tag 0.X.X
git push origin --tags
```

I don't have rights to push tags in the `fusionauth/charts` repo.  Are you doing anything different to push a tag to trigger a build?

**Comment by drpebcak** [comment]
I've been creating a release via the ui, which in turn creates a tag behind the surface. I'm cool with changes to the release flow as long as they are documented/understood.

**Pull request merged**
