### PR TITLE
Update workflow

### PR DESCRIPTION
**Pull request by johnjeffers**
**What this PR does / why we need it**:

Workflow file cleanup and action version updates
* Use `ubuntu-22.04` runner
* Use latest version of `chart-releaser`
* Use latest version of `actions/checkout`
* use `name` instead of `id` for job steps
* change branch name from `master` to `main` in `cr` release step
* Replace action that creates a kind cluster with one from a more official, up-to-date source

Update `CODEOWNERS` with FusionAuth owners only

Update `README.md`
* Replace Travis build status with Actions badge
* Update link to installation doc

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR breaks earlier versions

### CODE REVIEW

**Review by robotdan — APPROVED** [review]
Looks good to me. 

My preference is to keep all of repositories the same as it relates to the `master` or `main ` branch naming. I don't see any reason to rename all of our repos at this time, so we could either leave this repo as is using the `master` branch, or keep your change and it will just be a one off from the rest of our repositories.

**Comment by robotdan** [comment]
Looks like we also have a broken image link in the `README.md` up to you if we want to fix that now or not depending on if we want to continue to use Travis CI or not.

**Comment by johnjeffers** [comment]
> My preference is to keep all of repositories the same as it relates to the `master` or `main ` branch naming. I don't see any reason to rename all of our repos at this time, so we could either leave this repo as is using the `master` branch, or keep your change and it will just be a one off from the rest of our repositories.

I feel pretty strongly about not using `master`, so if you don't have a strong opinion about it, my preference is to leave it renamed to `main`.

**Comment by johnjeffers** [comment]
> Looks like we also have a broken image link in the `README.md` up to you if we want to fix that now or not depending on if we want to continue to use Travis CI or not.

Is this the broken link you're talking about? https://github.com/FusionAuth/charts/blob/main/README.md?plain=1#L1
If so, that change is part of this PR.

I don't see anything else related to Travis in the workflow, so I don't think we are using Travis for this anymore? If there's something I'm missing, let me know!

**Pull request merged**
