### PR TITLE
Feature/tpl values

### PR DESCRIPTION
**Pull request by SwitchTV-BenBettridge**
**What this PR does / why we need it**:
Adds support for using template strings inside `values.yaml` itself by using the [tpl function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) when referring to `.Values.app.*`, `.Values.search.*`, `.Values.database.*` and `.Values.ingress.hosts`.

Because the `tpl` function applies to strings, not integers, booleans, etc a small helper function has been created to check the value type and reduce boilerplate.

**Special notes for your reviewer**:

An example use-case for this (and how we are using this chart internally) is to allow for a central global configuration to be easily distributed to all sub-charts:

**Chart.yaml**
```
name: example
dependencies:
  - name: fusionauth
    version: 0.10.5
    repository: https://fusionauth.github.io/charts
  - name: webapp
    condition: webapp.enabled
    version: 0.0.1
    repository: https://charts.example.com
```

**values.yaml**
```
global:
  fusionauth_domain: fusionauth.example.com
  webapp_domain: webapp.example.com

fusionauth:
  ingress:
   hosts:
    - "{{ .Values.global.fusionauth_domain }}"

webapp:
  ingress:
    hosts:
      - "{{ .Values.global.webapp_domain }}"
    fusionauth_domain: "{{ .Values.global.fusionauth_domain }}"
```

### CODE REVIEW

**Comment by HeWhoWas** [comment]
@drpebcak - Just checking if there is any appetite for merging this PR? If it needs additional work I'm happy to put the effort in.

**Comment by mooreds** [comment]
cc @robotdan

**Comment by johnjeffers** [comment]
@SwitchTV-BenBettridge Apologies that this has sat for so long. I've recently started working at FusionAuth, and I'm taking on these lingering issues.

This seems to add a fair amount of complexity to the chart for what looks like a niche use case. Can you talk more about this? What problem does it solve? And more importantly, does this change the standard behavior of the chart if you don't need the templating feature? Sorry for my ignorance on this matter. I haven't seen this pattern before in a helm chart.

**Comment by johnjeffers** [comment]
Closing due to inactivity.

**Pull request closed without merging**
